buttons_array = [
    {
        "text": "0",
        "row": 4,
        "column": 0,
        "rowspan": False,
        "columnspan": 2,
        "sticky": "left_right",
    },
    {
        "text": "1",
        "row": 3,
        "column": 0,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "2",
        "row": 3,
        "column": 1,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "3",
        "row": 3,
        "column": 2,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "4",
        "row": 2,
        "column": 0,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "5",
        "row": 2,
        "column": 1,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "6",
        "row": 2,
        "column": 2,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "7",
        "row": 1,
        "column": 0,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "8",
        "row": 1,
        "column": 1,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "9",
        "row": 1,
        "column": 2,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": ".",
        "row": 4,
        "column": 2,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "-",
        "row": 1,
        "column": 3,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "+",
        "row": 0,
        "column": 3,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "/",
        "row": 0,
        "column": 2,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "*",
        "row": 0,
        "column": 1,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "c",
        "row": 0,
        "column": 0,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "Backspace",
        "row": 2,
        "column": 3,
        "rowspan": False,
        "columnspan": False,
        "sticky": "left_right",
    },
    {
        "text": "=",
        "row": 3,
        "column": 3,
        "rowspan": 2,
        "columnspan": False,
        "sticky": "up_down_left_right",
    },
]
